//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDoor
{
    using System;
    using System.Collections.Generic;
    
    public partial class bajaprod
    {
        public long idBaja { get; set; }
        public string idProductoFK { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Motivo { get; set; }
    
        public virtual bajaprodmotivo bajaprodmotivo { get; set; }
        public virtual producto producto { get; set; }
    }
}
