//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDoor
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente_seguim_galeria
    {
        public int id { get; set; }
        public Nullable<int> seguimiento_id { get; set; }
        public byte[] foto { get; set; }
    
        public virtual cliente_seguimiento cliente_seguimiento { get; set; }
    }
}
