//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDoor
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente_membresia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cliente_membresia()
        {
            this.pago_membresia = new HashSet<pago_membresia>();
        }
    
        public int id { get; set; }
        public string cliente_ci { get; set; }
        public int membresia_id { get; set; }
        public System.DateTime fecha_inicio { get; set; }
        public int precio { get; set; }
        public int descuento { get; set; }
        public System.DateTime fecha_fin { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual membresia membresia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pago_membresia> pago_membresia { get; set; }
    }
}
