//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDoor
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente_seguimiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cliente_seguimiento()
        {
            this.cliente_seguim_galeria = new HashSet<cliente_seguim_galeria>();
        }
    
        public int id { get; set; }
        public string cliente_ci { get; set; }
        public System.DateTime fecha { get; set; }
        public double peso { get; set; }
        public double altura { get; set; }
        public double hombros { get; set; }
        public double pecho { get; set; }
        public double biceps_relajado { get; set; }
        public double biceps_contraido { get; set; }
        public double antebrazo { get; set; }
        public double muneca { get; set; }
        public double abdomen { get; set; }
        public double cintura { get; set; }
        public double caderas { get; set; }
        public double muslo { get; set; }
        public double rodilla { get; set; }
        public double gemelos { get; set; }
        public double tobillo { get; set; }
    
        public virtual cliente cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cliente_seguim_galeria> cliente_seguim_galeria { get; set; }
    }
}
