//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDoor
{
    using System;
    using System.Collections.Generic;
    
    public partial class comisionpagada
    {
        public System.DateTime Fecha { get; set; }
        public long IdEmpleado { get; set; }
        public string Periodo { get; set; }
        public int Monto { get; set; }
    
        public virtual empleado empleado { get; set; }
    }
}
