//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDoor
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class minegocioEntities : DbContext
    {
        public minegocioEntities()
            : base("name=minegocioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<acceso> acceso { get; set; }
        public virtual DbSet<acceso_finger_print> acceso_finger_print { get; set; }
        public virtual DbSet<altaprod> altaprod { get; set; }
        public virtual DbSet<altaprodmotivo> altaprodmotivo { get; set; }
        public virtual DbSet<bajaprod> bajaprod { get; set; }
        public virtual DbSet<bajaprodmotivo> bajaprodmotivo { get; set; }
        public virtual DbSet<base_user_extend> base_user_extend { get; set; }
        public virtual DbSet<cajamostrador> cajamostrador { get; set; }
        public virtual DbSet<categoria_prod> categoria_prod { get; set; }
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<cliente_acceso> cliente_acceso { get; set; }
        public virtual DbSet<cliente_asistencia> cliente_asistencia { get; set; }
        public virtual DbSet<cliente_membresia> cliente_membresia { get; set; }
        public virtual DbSet<cliente_seguim_galeria> cliente_seguim_galeria { get; set; }
        public virtual DbSet<cliente_seguimiento> cliente_seguimiento { get; set; }
        public virtual DbSet<comisionpagada> comisionpagada { get; set; }
        public virtual DbSet<compra> compra { get; set; }
        public virtual DbSet<detallecompra> detallecompra { get; set; }
        public virtual DbSet<detalleocupacion> detalleocupacion { get; set; }
        public virtual DbSet<detalleventa> detalleventa { get; set; }
        public virtual DbSet<detnotaccompra> detnotaccompra { get; set; }
        public virtual DbSet<detnotacventa> detnotacventa { get; set; }
        public virtual DbSet<empleado> empleado { get; set; }
        public virtual DbSet<empleado_asistencia> empleado_asistencia { get; set; }
        public virtual DbSet<finger_print> finger_print { get; set; }
        public virtual DbSet<gasto> gasto { get; set; }
        public virtual DbSet<habitacion> habitacion { get; set; }
        public virtual DbSet<habitacion2> habitacion2 { get; set; }
        public virtual DbSet<habitacionajustes> habitacionajustes { get; set; }
        public virtual DbSet<listagasto> listagasto { get; set; }
        public virtual DbSet<marca> marca { get; set; }
        public virtual DbSet<membresia> membresia { get; set; }
        public virtual DbSet<modelo> modelo { get; set; }
        public virtual DbSet<notaccompra> notaccompra { get; set; }
        public virtual DbSet<notacventa> notacventa { get; set; }
        public virtual DbSet<ocupacionmanual> ocupacionmanual { get; set; }
        public virtual DbSet<ocupacionsensor> ocupacionsensor { get; set; }
        public virtual DbSet<pago_membresia> pago_membresia { get; set; }
        public virtual DbSet<pedidoc> pedidoc { get; set; }
        public virtual DbSet<privilegio> privilegio { get; set; }
        public virtual DbSet<producto> producto { get; set; }
        public virtual DbSet<proveedor> proveedor { get; set; }
        public virtual DbSet<recibocobrocuenta> recibocobrocuenta { get; set; }
        public virtual DbSet<recibopagocuenta> recibopagocuenta { get; set; }
        public virtual DbSet<serviciohabitacion> serviciohabitacion { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
        public virtual DbSet<venta> venta { get; set; }
        public virtual DbSet<view_asistencia> view_asistencia { get; set; }
        public virtual DbSet<view_cuentas_cobrar> view_cuentas_cobrar { get; set; }
        public virtual DbSet<view_pago_membresia> view_pago_membresia { get; set; }
        public virtual DbSet<view_pago_membresia_periodo> view_pago_membresia_periodo { get; set; }
        public virtual DbSet<viewaltaprod> viewaltaprod { get; set; }
        public virtual DbSet<viewbajaprod> viewbajaprod { get; set; }
        public virtual DbSet<viewcajamostrador> viewcajamostrador { get; set; }
        public virtual DbSet<viewcompra> viewcompra { get; set; }
        public virtual DbSet<viewdetalleingreso> viewdetalleingreso { get; set; }
        public virtual DbSet<viewdetcompra> viewdetcompra { get; set; }
        public virtual DbSet<viewdetnotaccompra> viewdetnotaccompra { get; set; }
        public virtual DbSet<viewdetnotacventa> viewdetnotacventa { get; set; }
        public virtual DbSet<viewdetocupacion> viewdetocupacion { get; set; }
        public virtual DbSet<viewdetventa> viewdetventa { get; set; }
        public virtual DbSet<viewgasto> viewgasto { get; set; }
        public virtual DbSet<viewnotaccompra> viewnotaccompra { get; set; }
        public virtual DbSet<viewnotacventa> viewnotacventa { get; set; }
        public virtual DbSet<viewproducto> viewproducto { get; set; }
        public virtual DbSet<viewsocio> viewsocio { get; set; }
        public virtual DbSet<viewsocio2> viewsocio2 { get; set; }
        public virtual DbSet<viewusuario> viewusuario { get; set; }
        public virtual DbSet<viewventa> viewventa { get; set; }
        public virtual DbSet<view_finger_print> view_finger_print { get; set; }
        public virtual DbSet<empleado_acceso> empleado_acceso { get; set; }
    
        public virtual int zcajam_abrir(Nullable<sbyte> numCaja, Nullable<int> idEmple, Nullable<int> montoIni)
        {
            var numCajaParameter = numCaja.HasValue ?
                new ObjectParameter("NumCaja", numCaja) :
                new ObjectParameter("NumCaja", typeof(sbyte));
    
            var idEmpleParameter = idEmple.HasValue ?
                new ObjectParameter("idEmple", idEmple) :
                new ObjectParameter("idEmple", typeof(int));
    
            var montoIniParameter = montoIni.HasValue ?
                new ObjectParameter("MontoIni", montoIni) :
                new ObjectParameter("MontoIni", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("zcajam_abrir", numCajaParameter, idEmpleParameter, montoIniParameter);
        }
    
        public virtual ObjectResult<zcajam_buscar_Result> zcajam_buscar(Nullable<System.DateTime> fecha)
        {
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("Fecha", fecha) :
                new ObjectParameter("Fecha", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<zcajam_buscar_Result>("zcajam_buscar", fechaParameter);
        }
    
        public virtual ObjectResult<zcajam_buscar2_Result> zcajam_buscar2(Nullable<System.DateTime> fecha, Nullable<System.TimeSpan> hora)
        {
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("Fecha", fecha) :
                new ObjectParameter("Fecha", typeof(System.DateTime));
    
            var horaParameter = hora.HasValue ?
                new ObjectParameter("Hora", hora) :
                new ObjectParameter("Hora", typeof(System.TimeSpan));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<zcajam_buscar2_Result>("zcajam_buscar2", fechaParameter, horaParameter);
        }
    
        public virtual int zcajam_get_fechafin(Nullable<sbyte> numCaja, Nullable<System.DateTime> fecha)
        {
            var numCajaParameter = numCaja.HasValue ?
                new ObjectParameter("NumCaja", numCaja) :
                new ObjectParameter("NumCaja", typeof(sbyte));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("Fecha", fecha) :
                new ObjectParameter("Fecha", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("zcajam_get_fechafin", numCajaParameter, fechaParameter);
        }
    
        public virtual int zcajam_get_fechaini(Nullable<sbyte> numCaja, ObjectParameter fecha)
        {
            var numCajaParameter = numCaja.HasValue ?
                new ObjectParameter("NumCaja", numCaja) :
                new ObjectParameter("NumCaja", typeof(sbyte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("zcajam_get_fechaini", numCajaParameter, fecha);
        }
    
        public virtual int zcajam_get_montoini(Nullable<sbyte> numCaja, ObjectParameter montoIni)
        {
            var numCajaParameter = numCaja.HasValue ?
                new ObjectParameter("NumCaja", numCaja) :
                new ObjectParameter("NumCaja", typeof(sbyte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("zcajam_get_montoini", numCajaParameter, montoIni);
        }
    
        public virtual int zcalc_devol_venta(Nullable<System.DateTime> fecha1, Nullable<System.DateTime> fecha2, ObjectParameter monto)
        {
            var fecha1Parameter = fecha1.HasValue ?
                new ObjectParameter("Fecha1", fecha1) :
                new ObjectParameter("Fecha1", typeof(System.DateTime));
    
            var fecha2Parameter = fecha2.HasValue ?
                new ObjectParameter("Fecha2", fecha2) :
                new ObjectParameter("Fecha2", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("zcalc_devol_venta", fecha1Parameter, fecha2Parameter, monto);
        }
    
        public virtual int zcalc_rec_venta(Nullable<System.DateTime> fecha1, Nullable<System.DateTime> fecha2, ObjectParameter monto)
        {
            var fecha1Parameter = fecha1.HasValue ?
                new ObjectParameter("Fecha1", fecha1) :
                new ObjectParameter("Fecha1", typeof(System.DateTime));
    
            var fecha2Parameter = fecha2.HasValue ?
                new ObjectParameter("Fecha2", fecha2) :
                new ObjectParameter("Fecha2", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("zcalc_rec_venta", fecha1Parameter, fecha2Parameter, monto);
        }
    
        public virtual ObjectResult<zcomprasxmes_Result> zcomprasxmes(Nullable<int> anho)
        {
            var anhoParameter = anho.HasValue ?
                new ObjectParameter("Anho", anho) :
                new ObjectParameter("Anho", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<zcomprasxmes_Result>("zcomprasxmes", anhoParameter);
        }
    
        public virtual int zdetalleocup_insert(Nullable<int> idVenta, Nullable<sbyte> idHab, Nullable<sbyte> idServHab, Nullable<short> tiemp, Nullable<int> prec, Nullable<int> subT)
        {
            var idVentaParameter = idVenta.HasValue ?
                new ObjectParameter("idVenta", idVenta) :
                new ObjectParameter("idVenta", typeof(int));
    
            var idHabParameter = idHab.HasValue ?
                new ObjectParameter("idHab", idHab) :
                new ObjectParameter("idHab", typeof(sbyte));
    
            var idServHabParameter = idServHab.HasValue ?
                new ObjectParameter("idServHab", idServHab) :
                new ObjectParameter("idServHab", typeof(sbyte));
    
            var tiempParameter = tiemp.HasValue ?
                new ObjectParameter("Tiemp", tiemp) :
                new ObjectParameter("Tiemp", typeof(short));
    
            var precParameter = prec.HasValue ?
                new ObjectParameter("Prec", prec) :
                new ObjectParameter("Prec", typeof(int));
    
            var subTParameter = subT.HasValue ?
                new ObjectParameter("SubT", subT) :
                new ObjectParameter("SubT", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("zdetalleocup_insert", idVentaParameter, idHabParameter, idServHabParameter, tiempParameter, precParameter, subTParameter);
        }
    
        public virtual ObjectResult<zgastoxmes_Result> zgastoxmes(Nullable<short> anho)
        {
            var anhoParameter = anho.HasValue ?
                new ObjectParameter("Anho", anho) :
                new ObjectParameter("Anho", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<zgastoxmes_Result>("zgastoxmes", anhoParameter);
        }
    
        public virtual ObjectResult<zhabitacion_buscar_Result> zhabitacion_buscar(Nullable<sbyte> idHab, Nullable<sbyte> idServHab)
        {
            var idHabParameter = idHab.HasValue ?
                new ObjectParameter("idHab", idHab) :
                new ObjectParameter("idHab", typeof(sbyte));
    
            var idServHabParameter = idServHab.HasValue ?
                new ObjectParameter("idServHab", idServHab) :
                new ObjectParameter("idServHab", typeof(sbyte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<zhabitacion_buscar_Result>("zhabitacion_buscar", idHabParameter, idServHabParameter);
        }
    
        public virtual ObjectResult<zhabitacion_buscar2_Result> zhabitacion_buscar2(Nullable<sbyte> nroHab)
        {
            var nroHabParameter = nroHab.HasValue ?
                new ObjectParameter("nroHab", nroHab) :
                new ObjectParameter("nroHab", typeof(sbyte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<zhabitacion_buscar2_Result>("zhabitacion_buscar2", nroHabParameter);
        }
    
        public virtual int zhabitacion_update(Nullable<sbyte> idHab, Nullable<sbyte> idServHab, string descrip, Nullable<int> prec)
        {
            var idHabParameter = idHab.HasValue ?
                new ObjectParameter("idHab", idHab) :
                new ObjectParameter("idHab", typeof(sbyte));
    
            var idServHabParameter = idServHab.HasValue ?
                new ObjectParameter("idServHab", idServHab) :
                new ObjectParameter("idServHab", typeof(sbyte));
    
            var descripParameter = descrip != null ?
                new ObjectParameter("Descrip", descrip) :
                new ObjectParameter("Descrip", typeof(string));
    
            var precParameter = prec.HasValue ?
                new ObjectParameter("Prec", prec) :
                new ObjectParameter("Prec", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("zhabitacion_update", idHabParameter, idServHabParameter, descripParameter, precParameter);
        }
    
        public virtual int zhabitacion_update2(Nullable<sbyte> idHab, Nullable<int> prec1, Nullable<int> prec2, Nullable<int> prec3)
        {
            var idHabParameter = idHab.HasValue ?
                new ObjectParameter("idHab", idHab) :
                new ObjectParameter("idHab", typeof(sbyte));
    
            var prec1Parameter = prec1.HasValue ?
                new ObjectParameter("Prec1", prec1) :
                new ObjectParameter("Prec1", typeof(int));
    
            var prec2Parameter = prec2.HasValue ?
                new ObjectParameter("Prec2", prec2) :
                new ObjectParameter("Prec2", typeof(int));
    
            var prec3Parameter = prec3.HasValue ?
                new ObjectParameter("Prec3", prec3) :
                new ObjectParameter("Prec3", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("zhabitacion_update2", idHabParameter, prec1Parameter, prec2Parameter, prec3Parameter);
        }
    
        public virtual ObjectResult<zhabitacion_viewall_Result> zhabitacion_viewall()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<zhabitacion_viewall_Result>("zhabitacion_viewall");
        }
    
        public virtual ObjectResult<zhabitacion_viewall2_Result> zhabitacion_viewall2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<zhabitacion_viewall2_Result>("zhabitacion_viewall2");
        }
    
        public virtual int zhabit_ajustes(Nullable<short> mEntrada, Nullable<short> mSalida, Nullable<short> toleranc)
        {
            var mEntradaParameter = mEntrada.HasValue ?
                new ObjectParameter("MEntrada", mEntrada) :
                new ObjectParameter("MEntrada", typeof(short));
    
            var mSalidaParameter = mSalida.HasValue ?
                new ObjectParameter("MSalida", mSalida) :
                new ObjectParameter("MSalida", typeof(short));
    
            var tolerancParameter = toleranc.HasValue ?
                new ObjectParameter("Toleranc", toleranc) :
                new ObjectParameter("Toleranc", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("zhabit_ajustes", mEntradaParameter, mSalidaParameter, tolerancParameter);
        }
    
        public virtual ObjectResult<zhabit_ajustes_view_Result> zhabit_ajustes_view()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<zhabit_ajustes_view_Result>("zhabit_ajustes_view");
        }
    
        public virtual ObjectResult<zingreso_busc_detalle_Result> zingreso_busc_detalle(Nullable<System.DateTime> fechaIni, Nullable<System.DateTime> fechaFin)
        {
            var fechaIniParameter = fechaIni.HasValue ?
                new ObjectParameter("FechaIni", fechaIni) :
                new ObjectParameter("FechaIni", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<zingreso_busc_detalle_Result>("zingreso_busc_detalle", fechaIniParameter, fechaFinParameter);
        }
    
        public virtual ObjectResult<zingreso_busc_resum_Result> zingreso_busc_resum(Nullable<System.DateTime> fechaIni, Nullable<System.DateTime> fechaFin)
        {
            var fechaIniParameter = fechaIni.HasValue ?
                new ObjectParameter("FechaIni", fechaIni) :
                new ObjectParameter("FechaIni", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<zingreso_busc_resum_Result>("zingreso_busc_resum", fechaIniParameter, fechaFinParameter);
        }
    
        public virtual ObjectResult<zingreso_busc_totales_Result> zingreso_busc_totales(Nullable<System.DateTime> fechaIni, Nullable<System.DateTime> fechaFin)
        {
            var fechaIniParameter = fechaIni.HasValue ?
                new ObjectParameter("FechaIni", fechaIni) :
                new ObjectParameter("FechaIni", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<zingreso_busc_totales_Result>("zingreso_busc_totales", fechaIniParameter, fechaFinParameter);
        }
    
        public virtual ObjectResult<znotacxmes_Result> znotacxmes(Nullable<int> anho)
        {
            var anhoParameter = anho.HasValue ?
                new ObjectParameter("Anho", anho) :
                new ObjectParameter("Anho", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<znotacxmes_Result>("znotacxmes", anhoParameter);
        }
    
        public virtual ObjectResult<znotavxmes_Result> znotavxmes(Nullable<int> anho)
        {
            var anhoParameter = anho.HasValue ?
                new ObjectParameter("Anho", anho) :
                new ObjectParameter("Anho", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<znotavxmes_Result>("znotavxmes", anhoParameter);
        }
    
        public virtual ObjectResult<zocupmanual_buscar_Result> zocupmanual_buscar(Nullable<System.DateTime> horaE, Nullable<System.DateTime> horaS, Nullable<sbyte> nroHabit)
        {
            var horaEParameter = horaE.HasValue ?
                new ObjectParameter("HoraE", horaE) :
                new ObjectParameter("HoraE", typeof(System.DateTime));
    
            var horaSParameter = horaS.HasValue ?
                new ObjectParameter("HoraS", horaS) :
                new ObjectParameter("HoraS", typeof(System.DateTime));
    
            var nroHabitParameter = nroHabit.HasValue ?
                new ObjectParameter("NroHabit", nroHabit) :
                new ObjectParameter("NroHabit", typeof(sbyte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<zocupmanual_buscar_Result>("zocupmanual_buscar", horaEParameter, horaSParameter, nroHabitParameter);
        }
    
        public virtual int zocupmanual_ins_in(Nullable<sbyte> nroHabit)
        {
            var nroHabitParameter = nroHabit.HasValue ?
                new ObjectParameter("nroHabit", nroHabit) :
                new ObjectParameter("nroHabit", typeof(sbyte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("zocupmanual_ins_in", nroHabitParameter);
        }
    
        public virtual int zocupmanual_ins_out(Nullable<sbyte> nroHabit, Nullable<int> idVenta)
        {
            var nroHabitParameter = nroHabit.HasValue ?
                new ObjectParameter("nroHabit", nroHabit) :
                new ObjectParameter("nroHabit", typeof(sbyte));
    
            var idVentaParameter = idVenta.HasValue ?
                new ObjectParameter("idVenta", idVenta) :
                new ObjectParameter("idVenta", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("zocupmanual_ins_out", nroHabitParameter, idVentaParameter);
        }
    
        public virtual int zocupmanual_ins_out2(Nullable<sbyte> nroHabit)
        {
            var nroHabitParameter = nroHabit.HasValue ?
                new ObjectParameter("nroHabit", nroHabit) :
                new ObjectParameter("nroHabit", typeof(sbyte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("zocupmanual_ins_out2", nroHabitParameter);
        }
    
        public virtual ObjectResult<zocupmanual_sinsalida_Result> zocupmanual_sinsalida(Nullable<sbyte> nroHabit)
        {
            var nroHabitParameter = nroHabit.HasValue ?
                new ObjectParameter("NroHabit", nroHabit) :
                new ObjectParameter("NroHabit", typeof(sbyte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<zocupmanual_sinsalida_Result>("zocupmanual_sinsalida", nroHabitParameter);
        }
    
        public virtual ObjectResult<zocupmanual_view_Result> zocupmanual_view(Nullable<System.DateTime> fecha)
        {
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("Fecha", fecha) :
                new ObjectParameter("Fecha", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<zocupmanual_view_Result>("zocupmanual_view", fechaParameter);
        }
    
        public virtual ObjectResult<zocupsensor_buscar_Result> zocupsensor_buscar(Nullable<System.DateTime> horaE, Nullable<System.DateTime> horaS, Nullable<sbyte> nroHabit)
        {
            var horaEParameter = horaE.HasValue ?
                new ObjectParameter("HoraE", horaE) :
                new ObjectParameter("HoraE", typeof(System.DateTime));
    
            var horaSParameter = horaS.HasValue ?
                new ObjectParameter("HoraS", horaS) :
                new ObjectParameter("HoraS", typeof(System.DateTime));
    
            var nroHabitParameter = nroHabit.HasValue ?
                new ObjectParameter("NroHabit", nroHabit) :
                new ObjectParameter("NroHabit", typeof(sbyte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<zocupsensor_buscar_Result>("zocupsensor_buscar", horaEParameter, horaSParameter, nroHabitParameter);
        }
    
        public virtual int zocupsensor_ins_in(Nullable<sbyte> nroHabit)
        {
            var nroHabitParameter = nroHabit.HasValue ?
                new ObjectParameter("NroHabit", nroHabit) :
                new ObjectParameter("NroHabit", typeof(sbyte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("zocupsensor_ins_in", nroHabitParameter);
        }
    
        public virtual int zocupsensor_ins_out(Nullable<sbyte> nroHabit)
        {
            var nroHabitParameter = nroHabit.HasValue ?
                new ObjectParameter("nroHabit", nroHabit) :
                new ObjectParameter("nroHabit", typeof(sbyte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("zocupsensor_ins_out", nroHabitParameter);
        }
    
        public virtual ObjectResult<zocupsensor_view_Result> zocupsensor_view(Nullable<System.DateTime> fecha)
        {
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("Fecha", fecha) :
                new ObjectParameter("Fecha", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<zocupsensor_view_Result>("zocupsensor_view", fechaParameter);
        }
    
        public virtual int zprivilegio_delete(Nullable<int> idPriv)
        {
            var idPrivParameter = idPriv.HasValue ?
                new ObjectParameter("idPriv", idPriv) :
                new ObjectParameter("idPriv", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("zprivilegio_delete", idPrivParameter);
        }
    
        public virtual int zprivilegio_insert(string rol_, Nullable<bool> prodConsult_, Nullable<bool> prodReg_, Nullable<bool> prodActualiz_, Nullable<bool> prodEliminar_, Nullable<bool> ventasConsult_, Nullable<bool> ventasReg_, Nullable<bool> comprasConsult_, Nullable<bool> comprasReg_, Nullable<bool> provConsult_, Nullable<bool> provReg_, Nullable<bool> provActualiz_, Nullable<bool> provEliminar_, Nullable<bool> empleAdmin_, Nullable<bool> usuAdmin_, Nullable<bool> finanzasAdmin_, Nullable<bool> habAdmin_, Nullable<bool> cuentasAdmin_, Nullable<bool> devolAutoriCli_, Nullable<bool> devolAutoriProv_)
        {
            var rol_Parameter = rol_ != null ?
                new ObjectParameter("Rol_", rol_) :
                new ObjectParameter("Rol_", typeof(string));
    
            var prodConsult_Parameter = prodConsult_.HasValue ?
                new ObjectParameter("ProdConsult_", prodConsult_) :
                new ObjectParameter("ProdConsult_", typeof(bool));
    
            var prodReg_Parameter = prodReg_.HasValue ?
                new ObjectParameter("ProdReg_", prodReg_) :
                new ObjectParameter("ProdReg_", typeof(bool));
    
            var prodActualiz_Parameter = prodActualiz_.HasValue ?
                new ObjectParameter("ProdActualiz_", prodActualiz_) :
                new ObjectParameter("ProdActualiz_", typeof(bool));
    
            var prodEliminar_Parameter = prodEliminar_.HasValue ?
                new ObjectParameter("ProdEliminar_", prodEliminar_) :
                new ObjectParameter("ProdEliminar_", typeof(bool));
    
            var ventasConsult_Parameter = ventasConsult_.HasValue ?
                new ObjectParameter("VentasConsult_", ventasConsult_) :
                new ObjectParameter("VentasConsult_", typeof(bool));
    
            var ventasReg_Parameter = ventasReg_.HasValue ?
                new ObjectParameter("VentasReg_", ventasReg_) :
                new ObjectParameter("VentasReg_", typeof(bool));
    
            var comprasConsult_Parameter = comprasConsult_.HasValue ?
                new ObjectParameter("ComprasConsult_", comprasConsult_) :
                new ObjectParameter("ComprasConsult_", typeof(bool));
    
            var comprasReg_Parameter = comprasReg_.HasValue ?
                new ObjectParameter("ComprasReg_", comprasReg_) :
                new ObjectParameter("ComprasReg_", typeof(bool));
    
            var provConsult_Parameter = provConsult_.HasValue ?
                new ObjectParameter("ProvConsult_", provConsult_) :
                new ObjectParameter("ProvConsult_", typeof(bool));
    
            var provReg_Parameter = provReg_.HasValue ?
                new ObjectParameter("ProvReg_", provReg_) :
                new ObjectParameter("ProvReg_", typeof(bool));
    
            var provActualiz_Parameter = provActualiz_.HasValue ?
                new ObjectParameter("ProvActualiz_", provActualiz_) :
                new ObjectParameter("ProvActualiz_", typeof(bool));
    
            var provEliminar_Parameter = provEliminar_.HasValue ?
                new ObjectParameter("ProvEliminar_", provEliminar_) :
                new ObjectParameter("ProvEliminar_", typeof(bool));
    
            var empleAdmin_Parameter = empleAdmin_.HasValue ?
                new ObjectParameter("EmpleAdmin_", empleAdmin_) :
                new ObjectParameter("EmpleAdmin_", typeof(bool));
    
            var usuAdmin_Parameter = usuAdmin_.HasValue ?
                new ObjectParameter("UsuAdmin_", usuAdmin_) :
                new ObjectParameter("UsuAdmin_", typeof(bool));
    
            var finanzasAdmin_Parameter = finanzasAdmin_.HasValue ?
                new ObjectParameter("FinanzasAdmin_", finanzasAdmin_) :
                new ObjectParameter("FinanzasAdmin_", typeof(bool));
    
            var habAdmin_Parameter = habAdmin_.HasValue ?
                new ObjectParameter("HabAdmin_", habAdmin_) :
                new ObjectParameter("HabAdmin_", typeof(bool));
    
            var cuentasAdmin_Parameter = cuentasAdmin_.HasValue ?
                new ObjectParameter("CuentasAdmin_", cuentasAdmin_) :
                new ObjectParameter("CuentasAdmin_", typeof(bool));
    
            var devolAutoriCli_Parameter = devolAutoriCli_.HasValue ?
                new ObjectParameter("DevolAutoriCli_", devolAutoriCli_) :
                new ObjectParameter("DevolAutoriCli_", typeof(bool));
    
            var devolAutoriProv_Parameter = devolAutoriProv_.HasValue ?
                new ObjectParameter("DevolAutoriProv_", devolAutoriProv_) :
                new ObjectParameter("DevolAutoriProv_", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("zprivilegio_insert", rol_Parameter, prodConsult_Parameter, prodReg_Parameter, prodActualiz_Parameter, prodEliminar_Parameter, ventasConsult_Parameter, ventasReg_Parameter, comprasConsult_Parameter, comprasReg_Parameter, provConsult_Parameter, provReg_Parameter, provActualiz_Parameter, provEliminar_Parameter, empleAdmin_Parameter, usuAdmin_Parameter, finanzasAdmin_Parameter, habAdmin_Parameter, cuentasAdmin_Parameter, devolAutoriCli_Parameter, devolAutoriProv_Parameter);
        }
    
        public virtual ObjectResult<zprivilegio_listar_Result> zprivilegio_listar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<zprivilegio_listar_Result>("zprivilegio_listar");
        }
    
        public virtual int zprivilegio_update(string rol_, Nullable<bool> prodConsult_, Nullable<bool> prodReg_, Nullable<bool> prodActualiz_, Nullable<bool> prodEliminar_, Nullable<bool> ventasConsult_, Nullable<bool> ventasReg_, Nullable<bool> comprasConsult_, Nullable<bool> comprasReg_, Nullable<bool> provConsult_, Nullable<bool> provReg_, Nullable<bool> provActualiz_, Nullable<bool> provEliminar_, Nullable<bool> empleAdmin_, Nullable<bool> usuAdmin_, Nullable<bool> finanzasAdmin_, Nullable<bool> habAdmin_, Nullable<bool> cuentasAdmin_, Nullable<bool> devolAutoriCli_, Nullable<bool> devolAutoriProv_, Nullable<int> idPrivilegio_)
        {
            var rol_Parameter = rol_ != null ?
                new ObjectParameter("Rol_", rol_) :
                new ObjectParameter("Rol_", typeof(string));
    
            var prodConsult_Parameter = prodConsult_.HasValue ?
                new ObjectParameter("ProdConsult_", prodConsult_) :
                new ObjectParameter("ProdConsult_", typeof(bool));
    
            var prodReg_Parameter = prodReg_.HasValue ?
                new ObjectParameter("ProdReg_", prodReg_) :
                new ObjectParameter("ProdReg_", typeof(bool));
    
            var prodActualiz_Parameter = prodActualiz_.HasValue ?
                new ObjectParameter("ProdActualiz_", prodActualiz_) :
                new ObjectParameter("ProdActualiz_", typeof(bool));
    
            var prodEliminar_Parameter = prodEliminar_.HasValue ?
                new ObjectParameter("ProdEliminar_", prodEliminar_) :
                new ObjectParameter("ProdEliminar_", typeof(bool));
    
            var ventasConsult_Parameter = ventasConsult_.HasValue ?
                new ObjectParameter("VentasConsult_", ventasConsult_) :
                new ObjectParameter("VentasConsult_", typeof(bool));
    
            var ventasReg_Parameter = ventasReg_.HasValue ?
                new ObjectParameter("VentasReg_", ventasReg_) :
                new ObjectParameter("VentasReg_", typeof(bool));
    
            var comprasConsult_Parameter = comprasConsult_.HasValue ?
                new ObjectParameter("ComprasConsult_", comprasConsult_) :
                new ObjectParameter("ComprasConsult_", typeof(bool));
    
            var comprasReg_Parameter = comprasReg_.HasValue ?
                new ObjectParameter("ComprasReg_", comprasReg_) :
                new ObjectParameter("ComprasReg_", typeof(bool));
    
            var provConsult_Parameter = provConsult_.HasValue ?
                new ObjectParameter("ProvConsult_", provConsult_) :
                new ObjectParameter("ProvConsult_", typeof(bool));
    
            var provReg_Parameter = provReg_.HasValue ?
                new ObjectParameter("ProvReg_", provReg_) :
                new ObjectParameter("ProvReg_", typeof(bool));
    
            var provActualiz_Parameter = provActualiz_.HasValue ?
                new ObjectParameter("ProvActualiz_", provActualiz_) :
                new ObjectParameter("ProvActualiz_", typeof(bool));
    
            var provEliminar_Parameter = provEliminar_.HasValue ?
                new ObjectParameter("ProvEliminar_", provEliminar_) :
                new ObjectParameter("ProvEliminar_", typeof(bool));
    
            var empleAdmin_Parameter = empleAdmin_.HasValue ?
                new ObjectParameter("EmpleAdmin_", empleAdmin_) :
                new ObjectParameter("EmpleAdmin_", typeof(bool));
    
            var usuAdmin_Parameter = usuAdmin_.HasValue ?
                new ObjectParameter("UsuAdmin_", usuAdmin_) :
                new ObjectParameter("UsuAdmin_", typeof(bool));
    
            var finanzasAdmin_Parameter = finanzasAdmin_.HasValue ?
                new ObjectParameter("FinanzasAdmin_", finanzasAdmin_) :
                new ObjectParameter("FinanzasAdmin_", typeof(bool));
    
            var habAdmin_Parameter = habAdmin_.HasValue ?
                new ObjectParameter("HabAdmin_", habAdmin_) :
                new ObjectParameter("HabAdmin_", typeof(bool));
    
            var cuentasAdmin_Parameter = cuentasAdmin_.HasValue ?
                new ObjectParameter("CuentasAdmin_", cuentasAdmin_) :
                new ObjectParameter("CuentasAdmin_", typeof(bool));
    
            var devolAutoriCli_Parameter = devolAutoriCli_.HasValue ?
                new ObjectParameter("DevolAutoriCli_", devolAutoriCli_) :
                new ObjectParameter("DevolAutoriCli_", typeof(bool));
    
            var devolAutoriProv_Parameter = devolAutoriProv_.HasValue ?
                new ObjectParameter("DevolAutoriProv_", devolAutoriProv_) :
                new ObjectParameter("DevolAutoriProv_", typeof(bool));
    
            var idPrivilegio_Parameter = idPrivilegio_.HasValue ?
                new ObjectParameter("idPrivilegio_", idPrivilegio_) :
                new ObjectParameter("idPrivilegio_", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("zprivilegio_update", rol_Parameter, prodConsult_Parameter, prodReg_Parameter, prodActualiz_Parameter, prodEliminar_Parameter, ventasConsult_Parameter, ventasReg_Parameter, comprasConsult_Parameter, comprasReg_Parameter, provConsult_Parameter, provReg_Parameter, provActualiz_Parameter, provEliminar_Parameter, empleAdmin_Parameter, usuAdmin_Parameter, finanzasAdmin_Parameter, habAdmin_Parameter, cuentasAdmin_Parameter, devolAutoriCli_Parameter, devolAutoriProv_Parameter, idPrivilegio_Parameter);
        }
    
        public virtual int zproducto_insert(string idprod, string idprov, Nullable<int> idcateg, string descrip, Nullable<int> costo, Nullable<int> precio1, Nullable<int> precio2, Nullable<int> precio3, Nullable<int> preciopack, Nullable<double> stock, Nullable<double> unidxpack, string porpack, byte[] foto, Nullable<sbyte> iva, Nullable<double> lado1, Nullable<double> lado2, Nullable<double> mxcaja)
        {
            var idprodParameter = idprod != null ?
                new ObjectParameter("idprod", idprod) :
                new ObjectParameter("idprod", typeof(string));
    
            var idprovParameter = idprov != null ?
                new ObjectParameter("idprov", idprov) :
                new ObjectParameter("idprov", typeof(string));
    
            var idcategParameter = idcateg.HasValue ?
                new ObjectParameter("idcateg", idcateg) :
                new ObjectParameter("idcateg", typeof(int));
    
            var descripParameter = descrip != null ?
                new ObjectParameter("descrip", descrip) :
                new ObjectParameter("descrip", typeof(string));
    
            var costoParameter = costo.HasValue ?
                new ObjectParameter("costo", costo) :
                new ObjectParameter("costo", typeof(int));
    
            var precio1Parameter = precio1.HasValue ?
                new ObjectParameter("precio1", precio1) :
                new ObjectParameter("precio1", typeof(int));
    
            var precio2Parameter = precio2.HasValue ?
                new ObjectParameter("precio2", precio2) :
                new ObjectParameter("precio2", typeof(int));
    
            var precio3Parameter = precio3.HasValue ?
                new ObjectParameter("precio3", precio3) :
                new ObjectParameter("precio3", typeof(int));
    
            var preciopackParameter = preciopack.HasValue ?
                new ObjectParameter("preciopack", preciopack) :
                new ObjectParameter("preciopack", typeof(int));
    
            var stockParameter = stock.HasValue ?
                new ObjectParameter("stock", stock) :
                new ObjectParameter("stock", typeof(double));
    
            var unidxpackParameter = unidxpack.HasValue ?
                new ObjectParameter("unidxpack", unidxpack) :
                new ObjectParameter("unidxpack", typeof(double));
    
            var porpackParameter = porpack != null ?
                new ObjectParameter("porpack", porpack) :
                new ObjectParameter("porpack", typeof(string));
    
            var fotoParameter = foto != null ?
                new ObjectParameter("foto", foto) :
                new ObjectParameter("foto", typeof(byte[]));
    
            var ivaParameter = iva.HasValue ?
                new ObjectParameter("iva", iva) :
                new ObjectParameter("iva", typeof(sbyte));
    
            var lado1Parameter = lado1.HasValue ?
                new ObjectParameter("lado1", lado1) :
                new ObjectParameter("lado1", typeof(double));
    
            var lado2Parameter = lado2.HasValue ?
                new ObjectParameter("lado2", lado2) :
                new ObjectParameter("lado2", typeof(double));
    
            var mxcajaParameter = mxcaja.HasValue ?
                new ObjectParameter("mxcaja", mxcaja) :
                new ObjectParameter("mxcaja", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("zproducto_insert", idprodParameter, idprovParameter, idcategParameter, descripParameter, costoParameter, precio1Parameter, precio2Parameter, precio3Parameter, preciopackParameter, stockParameter, unidxpackParameter, porpackParameter, fotoParameter, ivaParameter, lado1Parameter, lado2Parameter, mxcajaParameter);
        }
    
        public virtual int zproducto_update(string idprod, string idprov, Nullable<int> idcateg, string descrip, Nullable<int> cost, Nullable<int> prec1, Nullable<int> prec2, Nullable<int> prec3, Nullable<int> precPack, Nullable<double> cantunit, Nullable<double> unidxpak, string porpak, byte[] foti, string oldidProd, Nullable<sbyte> iva_, Nullable<double> lado1_, Nullable<double> lado2_, Nullable<double> mxcaja_)
        {
            var idprodParameter = idprod != null ?
                new ObjectParameter("idprod", idprod) :
                new ObjectParameter("idprod", typeof(string));
    
            var idprovParameter = idprov != null ?
                new ObjectParameter("idprov", idprov) :
                new ObjectParameter("idprov", typeof(string));
    
            var idcategParameter = idcateg.HasValue ?
                new ObjectParameter("idcateg", idcateg) :
                new ObjectParameter("idcateg", typeof(int));
    
            var descripParameter = descrip != null ?
                new ObjectParameter("descrip", descrip) :
                new ObjectParameter("descrip", typeof(string));
    
            var costParameter = cost.HasValue ?
                new ObjectParameter("Cost", cost) :
                new ObjectParameter("Cost", typeof(int));
    
            var prec1Parameter = prec1.HasValue ?
                new ObjectParameter("Prec1", prec1) :
                new ObjectParameter("Prec1", typeof(int));
    
            var prec2Parameter = prec2.HasValue ?
                new ObjectParameter("Prec2", prec2) :
                new ObjectParameter("Prec2", typeof(int));
    
            var prec3Parameter = prec3.HasValue ?
                new ObjectParameter("Prec3", prec3) :
                new ObjectParameter("Prec3", typeof(int));
    
            var precPackParameter = precPack.HasValue ?
                new ObjectParameter("PrecPack", precPack) :
                new ObjectParameter("PrecPack", typeof(int));
    
            var cantunitParameter = cantunit.HasValue ?
                new ObjectParameter("cantunit", cantunit) :
                new ObjectParameter("cantunit", typeof(double));
    
            var unidxpakParameter = unidxpak.HasValue ?
                new ObjectParameter("unidxpak", unidxpak) :
                new ObjectParameter("unidxpak", typeof(double));
    
            var porpakParameter = porpak != null ?
                new ObjectParameter("porpak", porpak) :
                new ObjectParameter("porpak", typeof(string));
    
            var fotiParameter = foti != null ?
                new ObjectParameter("foti", foti) :
                new ObjectParameter("foti", typeof(byte[]));
    
            var oldidProdParameter = oldidProd != null ?
                new ObjectParameter("oldidProd", oldidProd) :
                new ObjectParameter("oldidProd", typeof(string));
    
            var iva_Parameter = iva_.HasValue ?
                new ObjectParameter("Iva_", iva_) :
                new ObjectParameter("Iva_", typeof(sbyte));
    
            var lado1_Parameter = lado1_.HasValue ?
                new ObjectParameter("lado1_", lado1_) :
                new ObjectParameter("lado1_", typeof(double));
    
            var lado2_Parameter = lado2_.HasValue ?
                new ObjectParameter("lado2_", lado2_) :
                new ObjectParameter("lado2_", typeof(double));
    
            var mxcaja_Parameter = mxcaja_.HasValue ?
                new ObjectParameter("mxcaja_", mxcaja_) :
                new ObjectParameter("mxcaja_", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("zproducto_update", idprodParameter, idprovParameter, idcategParameter, descripParameter, costParameter, prec1Parameter, prec2Parameter, prec3Parameter, precPackParameter, cantunitParameter, unidxpakParameter, porpakParameter, fotiParameter, oldidProdParameter, iva_Parameter, lado1_Parameter, lado2_Parameter, mxcaja_Parameter);
        }
    
        public virtual ObjectResult<zrecibocobroxmes_Result> zrecibocobroxmes(Nullable<int> anho)
        {
            var anhoParameter = anho.HasValue ?
                new ObjectParameter("Anho", anho) :
                new ObjectParameter("Anho", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<zrecibocobroxmes_Result>("zrecibocobroxmes", anhoParameter);
        }
    
        public virtual ObjectResult<zrecibopagoxmes_Result> zrecibopagoxmes(Nullable<int> anho)
        {
            var anhoParameter = anho.HasValue ?
                new ObjectParameter("Anho", anho) :
                new ObjectParameter("Anho", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<zrecibopagoxmes_Result>("zrecibopagoxmes", anhoParameter);
        }
    
        public virtual ObjectResult<zservhab_buscar_Result> zservhab_buscar(Nullable<sbyte> idServHabit)
        {
            var idServHabitParameter = idServHabit.HasValue ?
                new ObjectParameter("idServHabit", idServHabit) :
                new ObjectParameter("idServHabit", typeof(sbyte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<zservhab_buscar_Result>("zservhab_buscar", idServHabitParameter);
        }
    
        public virtual int zservhab_update(string descrip1, string descrip2, string descrip3, Nullable<short> tiempo1, Nullable<short> tiempo2, Nullable<System.TimeSpan> horaE, Nullable<System.TimeSpan> horaS)
        {
            var descrip1Parameter = descrip1 != null ?
                new ObjectParameter("Descrip1", descrip1) :
                new ObjectParameter("Descrip1", typeof(string));
    
            var descrip2Parameter = descrip2 != null ?
                new ObjectParameter("Descrip2", descrip2) :
                new ObjectParameter("Descrip2", typeof(string));
    
            var descrip3Parameter = descrip3 != null ?
                new ObjectParameter("Descrip3", descrip3) :
                new ObjectParameter("Descrip3", typeof(string));
    
            var tiempo1Parameter = tiempo1.HasValue ?
                new ObjectParameter("Tiempo1", tiempo1) :
                new ObjectParameter("Tiempo1", typeof(short));
    
            var tiempo2Parameter = tiempo2.HasValue ?
                new ObjectParameter("Tiempo2", tiempo2) :
                new ObjectParameter("Tiempo2", typeof(short));
    
            var horaEParameter = horaE.HasValue ?
                new ObjectParameter("HoraE", horaE) :
                new ObjectParameter("HoraE", typeof(System.TimeSpan));
    
            var horaSParameter = horaS.HasValue ?
                new ObjectParameter("HoraS", horaS) :
                new ObjectParameter("HoraS", typeof(System.TimeSpan));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("zservhab_update", descrip1Parameter, descrip2Parameter, descrip3Parameter, tiempo1Parameter, tiempo2Parameter, horaEParameter, horaSParameter);
        }
    
        public virtual ObjectResult<zusuario_buscarxci_Result> zusuario_buscarxci(Nullable<int> cI)
        {
            var cIParameter = cI.HasValue ?
                new ObjectParameter("CI", cI) :
                new ObjectParameter("CI", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<zusuario_buscarxci_Result>("zusuario_buscarxci", cIParameter);
        }
    
        public virtual ObjectResult<zusuario_buscarxusu_Result> zusuario_buscarxusu(string usu)
        {
            var usuParameter = usu != null ?
                new ObjectParameter("Usu", usu) :
                new ObjectParameter("Usu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<zusuario_buscarxusu_Result>("zusuario_buscarxusu", usuParameter);
        }
    
        public virtual int zusuario_ins(string usu, string pass, Nullable<int> priv, Nullable<int> emple)
        {
            var usuParameter = usu != null ?
                new ObjectParameter("Usu", usu) :
                new ObjectParameter("Usu", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("Pass", pass) :
                new ObjectParameter("Pass", typeof(string));
    
            var privParameter = priv.HasValue ?
                new ObjectParameter("Priv", priv) :
                new ObjectParameter("Priv", typeof(int));
    
            var empleParameter = emple.HasValue ?
                new ObjectParameter("Emple", emple) :
                new ObjectParameter("Emple", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("zusuario_ins", usuParameter, passParameter, privParameter, empleParameter);
        }
    
        public virtual int zusuario_update(Nullable<int> idUsu, string usu, string pas, Nullable<int> idPriv, Nullable<int> idEmple)
        {
            var idUsuParameter = idUsu.HasValue ?
                new ObjectParameter("idUsu", idUsu) :
                new ObjectParameter("idUsu", typeof(int));
    
            var usuParameter = usu != null ?
                new ObjectParameter("Usu", usu) :
                new ObjectParameter("Usu", typeof(string));
    
            var pasParameter = pas != null ?
                new ObjectParameter("Pas", pas) :
                new ObjectParameter("Pas", typeof(string));
    
            var idPrivParameter = idPriv.HasValue ?
                new ObjectParameter("idPriv", idPriv) :
                new ObjectParameter("idPriv", typeof(int));
    
            var idEmpleParameter = idEmple.HasValue ?
                new ObjectParameter("idEmple", idEmple) :
                new ObjectParameter("idEmple", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("zusuario_update", idUsuParameter, usuParameter, pasParameter, idPrivParameter, idEmpleParameter);
        }
    
        public virtual ObjectResult<zventasxdia_Result> zventasxdia(Nullable<int> anho, Nullable<int> mes)
        {
            var anhoParameter = anho.HasValue ?
                new ObjectParameter("Anho", anho) :
                new ObjectParameter("Anho", typeof(int));
    
            var mesParameter = mes.HasValue ?
                new ObjectParameter("Mes", mes) :
                new ObjectParameter("Mes", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<zventasxdia_Result>("zventasxdia", anhoParameter, mesParameter);
        }
    
        public virtual ObjectResult<zventasxmes_Result> zventasxmes(Nullable<int> anho)
        {
            var anhoParameter = anho.HasValue ?
                new ObjectParameter("Anho", anho) :
                new ObjectParameter("Anho", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<zventasxmes_Result>("zventasxmes", anhoParameter);
        }
    }
}
