//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDoor
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalleocupacion
    {
        public long idVentaFK { get; set; }
        public byte idHabFK { get; set; }
        public byte idServHabFk { get; set; }
        public int Tiempo { get; set; }
        public long Precio { get; set; }
        public long SubTotal { get; set; }
    
        public virtual habitacion2 habitacion2 { get; set; }
        public virtual serviciohabitacion serviciohabitacion { get; set; }
        public virtual venta venta { get; set; }
    }
}
