//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDoor
{
    using System;
    using System.Collections.Generic;
    
    public partial class detallecompra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public detallecompra()
        {
            this.detnotaccompra = new HashSet<detnotaccompra>();
        }
    
        public long idCompraFK { get; set; }
        public string idProductoFK { get; set; }
        public long Unidades { get; set; }
        public long Precio { get; set; }
        public string Obs { get; set; }
    
        public virtual compra compra { get; set; }
        public virtual producto producto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detnotaccompra> detnotaccompra { get; set; }
    }
}
