//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDoor
{
    using System;
    using System.Collections.Generic;
    
    public partial class detnotaccompra
    {
        public long idNotaFK { get; set; }
        public long idCompraFK { get; set; }
        public string idProductoFK { get; set; }
        public long Unidades { get; set; }
    
        public virtual detallecompra detallecompra { get; set; }
        public virtual notaccompra notaccompra { get; set; }
    }
}
