//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDoor
{
    using System;
    using System.Collections.Generic;
    
    public partial class empleado_acceso
    {
        public int id { get; set; }
        public long empleado_ci { get; set; }
        public int acceso_id { get; set; }
    
        public virtual acceso acceso { get; set; }
        public virtual empleado empleado { get; set; }
    }
}
