//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDoor
{
    using System;
    using System.Collections.Generic;
    
    public partial class pago_membresia
    {
        public int id { get; set; }
        public int cliente_membresia_id { get; set; }
        public System.DateTime fecha { get; set; }
        public int monto { get; set; }
    
        public virtual cliente_membresia cliente_membresia { get; set; }
    }
}
