//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDoor
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_cuentas_cobrar
    {
        public Nullable<long> id { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string CI { get; set; }
        public string Clien { get; set; }
        public string concepto { get; set; }
        public Nullable<System.DateTime> Vto { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<decimal> Entregado { get; set; }
        public Nullable<double> Saldo { get; set; }
    }
}
