//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDoor
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewdetcompra
    {
        public long idCompraFK { get; set; }
        public string idProducto { get; set; }
        public string Descripcion { get; set; }
        public long Unidades { get; set; }
        public long Precio { get; set; }
        public double Importe { get; set; }
    }
}
