//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDoor
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewcajamostrador
    {
        public string Empleado { get; set; }
        public byte NroCaja { get; set; }
        public Nullable<System.DateTime> FechaIni { get; set; }
        public Nullable<System.TimeSpan> HoraIni { get; set; }
        public long MontoInicial { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public Nullable<System.TimeSpan> HoraFin { get; set; }
        public Nullable<int> MontoFinal { get; set; }
    }
}
