//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDoor
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewcompra
    {
        public Nullable<long> idCompra { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string RUC { get; set; }
        public string Proveed { get; set; }
        public Nullable<double> Total { get; set; }
        public string Cancelado { get; set; }
        public Nullable<long> Entregado { get; set; }
        public Nullable<System.DateTime> Vto { get; set; }
    }
}
