//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDoor
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewsocio2
    {
        public string cedula { get; set; }
        public string Nombre { get; set; }
        public string membresia { get; set; }
        public string Telefono { get; set; }
        public string acceso { get; set; }
        public string Alias { get; set; }
        public string Direccion { get; set; }
        public Nullable<System.DateTime> fecha_inicio { get; set; }
        public byte[] Foto { get; set; }
        public Nullable<sbyte> Activo { get; set; }
        public double Saldo { get; set; }
        public string estado { get; set; }
    }
}
