//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDoor
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewproducto
    {
        public string idProducto { get; set; }
        public string ProveedorFK { get; set; }
        public string Descripcion { get; set; }
        public long Costo { get; set; }
        public long Precio1 { get; set; }
        public long Precio2 { get; set; }
        public string PorPack { get; set; }
        public Nullable<long> PrecioPack { get; set; }
        public string Categoria { get; set; }
    }
}
