//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDoor
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewaltaprod
    {
        public long idAlta { get; set; }
        public System.DateTime Fecha { get; set; }
        public string idProductoFK { get; set; }
        public string Descripcion { get; set; }
        public string Motivo { get; set; }
    }
}
