//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDoor
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewdetalleingreso
    {
        public Nullable<long> Comprobante { get; set; }
        public string Cliente { get; set; }
        public string Descripcion { get; set; }
        public string MedioPago { get; set; }
        public Nullable<double> Monto { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    }
}
